import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export const generateScorecardPDF = (
  candidate,
  scores,
  totalScore,
  summary,
  pdfPath,
) => {
  return new Promise((resolve, reject) => {
    try {
      const dir = path.dirname(pdfPath);

      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      if (fs.existsSync(pdfPath)) {
        fs.unlinkSync(pdfPath);
      }
       const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(pdfPath);
      doc.pipe(stream);

      const totalQuestions = scores.length;
      const maxScore = totalQuestions * 10;
      const percentage = ((totalScore / maxScore) * 100).toFixed(2);

      let rating = "Needs Improvement";
      if (percentage >= 85) rating = "Excellent";
      else if (percentage >= 70) rating = "Very Good";
      else if (percentage >= 50) rating = "Good";

      /* ================= HEADER ================= */

      doc
        .fontSize(22)
        .fillColor("#1a237e")
        .text("INTERVIEW EVALUATION REPORT", {
          align: "center",
        });

      doc.moveDown(2);

      /* ================= CANDIDATE INFO ================= */

      doc
        .fontSize(14)
        .fillColor("#000")
        .text("Candidate Details", { underline: true });

      doc.moveDown(0.8);

      doc.fontSize(12);
      doc.text(`Name: ${candidate.name}`);
      doc.text(`Email: ${candidate.email}`);
      doc.text(`Interview Date: ${new Date().toLocaleDateString()}`);
      doc.moveDown();

      doc.text(`Total Questions: ${totalQuestions}`);
      doc.text(`Maximum Score: ${maxScore}`);
      doc.text(`Score Achieved: ${totalScore}`);
      doc.text(`Percentage: ${percentage}%`);
      doc.text(`Overall Rating: ${rating}`);

      doc.moveDown(2);

      /* ================= DETAILED SCORES TABLE ================= */

      doc
        .fontSize(14)
        .fillColor("#000")
        .text("Detailed Evaluation", { underline: true });

      doc.moveDown(1);

      const tableTop = doc.y;
      const itemSpacing = 20;

      doc.fontSize(12).text("Q#", 50, tableTop);
      doc.text("Score", 100, tableTop);
      doc.text("Feedback", 170, tableTop);

      doc.moveDown();

      scores.forEach((item, index) => {
        const y = tableTop + (index + 1) * itemSpacing;

        doc.text(`${index + 1}`, 50, y);
        doc.text(`${item.score}/10`, 100, y);
        doc.text(item.feedback || "No feedback provided", 170, y, {
          width: 350,
        });
      });

      doc.moveDown(scores.length + 2);

      /* ================= SUMMARY ================= */

      doc
        .moveDown(2)
        .fontSize(14)
        .text("Performance Summary", { underline: true });

      doc.moveDown(1);

      doc.fontSize(12).fillColor("#333").text(summary, {
        align: "justify",
      });

      /* ================= FOOTER ================= */

      doc.moveDown(3);
      doc
        .fontSize(10)
        .fillColor("gray")
        .text("Generated by Interview Evaluation System", {
          align: "center",
        });

      doc.end();

      stream.on("finish", () => resolve(pdfPath));
      stream.on("error", (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
};
